### PR TITLE
Fix to work with new async DataSource

### PR DESCRIPTION
**Pull request by hacker-cb**

### CODE REVIEW

**Comment by BenDol** [comment]
Please merge this against `release_1.0` thanks!

**Comment by BenDol** [comment]
Never mind just realized this is the sample repository :+1:

**Comment by BenDol** [comment]
Already reworked this, however pager didn't work when I tested it. Can you test it with my latest changes in `release_1.0`?

**Comment by hacker-cb** [comment]
I have checked with my master branches, all works fine:

https://github.com/Hacker-CB/gwt-material-table/commit/5bd747a414b18ef575090cfa05e94c0531a9277d
https://github.com/Hacker-CB/gwt-material-table-sample/commit/4260d99bd6acd62b9b4a5c0ac2a452587fc83fab

Seems that problem is after commit: https://github.com/GwtMaterialDesign/gwt-material-table-sample/commit/1f2b93773d3380e98124ad2da1e2f326a064ae47.

Please revert this commit and merge with my master. After all should work fine.

**Comment by hacker-cb** [comment]
You have asked me to make this work but you have also commited similar changes. So result is fail.

**Comment by BenDol** [comment]
@Hacker-CB sorry I never asked this, I didn't see the message that @kevzlou7979 made. My apologies, I had already done it before he asked. Also, the problem is to do with `MaterialDataPager` returning `startIndex` 1. Will look into a fix tomorrow. Thanks for all the contribution so far it is much appreciated.

**Comment by hacker-cb** [comment]
Ok, please look carefully to my changes and make modifications to master manually if needed.

**Pull request closed without merging**
